[project]
name = "async-provisionig"
version = "0.1.0"
description = "асинхронный запуск процесса активации оборудования"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "fastapi==0.115.14",
    "uvicorn==0.34.3",
]

[dependency-groups]
dev = [
    "ruff>=0.12.1",
]
